config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :messages do
    resources :comments
  end
  root 'messages#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  #validates  :content, presence: true, length: { minimum: 10, maximum: 255 }
  belongs_to :message
  belongs_to :user
end

app/models/message.rb
class Message < ApplicationRecord
  validates :title, presence: true, length: { minimum: 6, maximum: 45 }
  validates :description, presence: true, length: { minimum: 10, maximum: 300 }
  belongs_to :user
  has_many :comments, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  has_many :messages
  has_many :comments
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  before_action :find_messege, only: [:create, :edit, :update, :destroy]
  before_action :find_comment, only: [:edit, :update, :destroy]

  def create
    @comment = @message.comments.create(comment_params)
    @comment.user_id = current_user.id

    if @comment.save
      redirect_to message_path(@message)
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @comment.update(comment_params)
      redirect_to message_path(@message)
    else
      render 'edit'
    end
  end

  def destroy
    @comment.destroy
    redirect_to message_path(@message)
  end

  private

  def comment_params
    params.require(:comment).permit(:content)
  end

  def find_messege
    @message = Message.find(params[:message_id])
  end

  def find_comment
    @comment = @message.comments.find(params[:id])
  end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :find_message, only: [:show, :edit, :update, :destroy]

  def index
    @messages = Message.all.order("created_at DESC")
  end

  def show
  end

  def new
    @message = current_user.messages.build 
  end

  def create
    @message = current_user.messages.build(message_params)

    if @message.save
      redirect_to root_path
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @message.update(message_params)
      redirect_to message_params
    else
      render 'edit'
    end
  end

  def destroy
    @message.destroy
    redirect_to root_path
  end

  private

  def message_params
    params.require(:message).permit(:title, :description)
  end

  def find_message
    @message = Message.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/comments/_comment.html.erb
<div>
  <p class="text-lg"><%= comment.content %></p>
  <p class="text-green-400 text-sm bold">By <%= comment.user.email %> <%= time_ago_in_words(comment.created_at)%> ago</p>

  <div>
    <% if user_signed_in? %>
      <% if comment.user_id == current_user.id %>
        <%= link_to "Edit", edit_message_comment_path(comment.message, comment),
            class: "text-blue-300 hover:text-blue-700 underline" %>
        <%= link_to "Delete", message_comment_path(comment.message, comment),
            method: :delete, data: { confirm: "Are you sure?" },
            class: "text-red-200 hover:text-red-600 underline" %>
      <% end %>
    <% end %>

  </div>
</div>

app/views/comments/_form.html.erb
<%= simple_form_for ([ @message, @message.comments.build]) do |f| %>
  <%= f.input :content, label: "Comments",
              label_html: { class: "uppercase tracking-wide text-black text-xs font-bold mb-2"}, 
              input_html: { autocomplete: "description", 
                            class: "w-full h-40 bg-gray-200 text-black border border-gray-200 rounded py-3 px-4 mb-3" } 
  %>

  <%= f.button :submit, class: "bg-blue-400 hover:bg-blue-500 text-white uppercase text-s mx-auto p-2 rounded m-2" %>
<% end %>

app/views/comments/edit.html.erb
<div class="container mx-auto">
  <h2 class="text-blue-600 text-2xl uppercase">Edit Comment</h2>
  <%= simple_form_for ([ @message, @comment]) do |f| %>
    <%= f.input :content, label: "Comments",
                label_html: { class: "uppercase tracking-wide text-black text-xs font-bold mb-2"}, 
                input_html: { autocomplete: "description", 
                              class: "w-full h-40 bg-gray-200 text-black border border-gray-200 rounded py-3 px-4 mb-3" } 
    %>

    <%= f.button :submit, class: "bg-blue-400 hover:bg-blue-500 text-white uppercase text-s mx-auto p-2 rounded m-2" %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SportsForum</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <nav class="bg-indigo-500 shadow-lg">
      <div class="container mx-auto">
        <div class="sm:flex justify-between">
          <%= link_to "Sport Fan Forum", root_path,  class: "text-white text-2xl font-bold p-3 uppercase" %>
          <ul class="text-gray-300 sm:self-center text-xl border-t sm:border-none">
            <% if user_signed_in? %>
              <li class="sm:inline-block">
                <%= link_to "Create Post", new_message_path, class: "p-3 hover:text-white" %>
              </li>
            <% end %>
            <% if current_user.present?%>
              <li class="sm:inline-block">
                <%= link_to "Sing Out", destroy_user_session_path, method: :delete, class: "p-3 hover:text-white" %>
              </li>
            <% else %>
              <li class="sm:inline-block">
                <%= link_to "Log In", new_user_session_path, class: "p-3 hover:text-white" %>
              </li>
              <li class="sm:inline-block">
                <%= link_to "Sing Up", new_user_registration_path, class: "p-3 hover:text-white" %>
              </li>
            <% end %>
          </ul>
        </div>
      </div>
    </nav>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <div class="pt-4">
      <%= yield %>
    </div>
  </body>
</html>

app/views/messages/_form.html.erb
<%= simple_form_for @message do |f| %>
  <%= f.input :title, label: "Message Title",
              label_html: { class: "uppercase tracking-wide text-black text-xs font-bold mb-2"}, 
              input_html: { autocomplete: "title", 
                            class: "w-full bg-gray-200 text-black border border-gray-200 rounded py-3 px-4 mb-3" } 
  %>
  <%= f.input :description,
              label_html: { class: "uppercase tracking-wide text-black text-xs font-bold mb-2"}, 
              input_html: { autocomplete: "description", 
                            class: "w-full h-40 bg-gray-200 text-black border border-gray-200 rounded py-3 px-4 mb-3" } 
  %>

  <%= f.button :submit, class: "bg-gray-400 hover:bg-gray-500 text-white uppercase text-s mx-auto p-2 rounded m-2" %>
<% end %>

app/views/messages/edit.html.erb
<div class="container mx-auto">
  <div class="">
    <h1 class="text-blue-400 text-3xl uppercase">Edit Post</h1>
  </div>
  <div class="container mx-auto">
    <%= render 'form' %>
  </div>
  
</div>

app/views/messages/index.html.erb
<% @messages.each do |message|%>
  <div class="container mx-auto">
    <div>
      <h2 class="text-gray-800 text-2xl bold"><%= message.title %></h2>
      <div class="p-4">
        <%= link_to "Join Discossion!", message, 
            class: "border-2 border-blue-400 hover:border-blue-500 text-gray-700 hover:text-blue-500 text-sm uppercase mx-auto p-2 rounded m-4" %>
      </div>
    </div>

  </div>
<% end %>

<div class="container mx-auto pt-2">
  <%= link_to "Post Message", new_message_path, 
      class: "border-2 border-green-400 hover:border-green-500 text-gray-700 hover:text--500 text-sm uppercase mx-auto p-2 rounded m-4"%>
</div>

app/views/messages/new.html.erb
<div class="container mx-auto">
  <div class="">
    <h1 class="text-blue-400 text-3xl uppercase">Post Message</h1>
  </div>
  <div class="container mx-auto">
    <%= render 'form' %>
  </div>
  
</div>

app/views/messages/show.html.erb
<div class="container mx-auto">
  <div class="p-4">
    <h2 class="text-blue-600 text-2xl uppercase "><%= @message.title %></h2>
    <p class="text-sm bold"><%= time_ago_in_words(@message.created_at)%> ago</p>
    <p class="text-lg"><%= @message.description %></p>

  </div>

  <div class="p-4">
    <h2 class="text-blue-600 text-2xl uppercase">Comments</h2>
    <p class="text-sm bold"><%= render @message.comments %></p>
    <h3 class="text-blue-800 text-sm uppercase">Join Discossion</h3>
    <%= render 'comments/form' %>
  </div>
</div>
<div class="container mx-auto pt-2 flex">
  <%= link_to "Back", root_path,
        class: "border-2 
                border-indigo-400 
                hover:border-indigo-500 
                text-gray-700 
                hover:text-indigo-800
                hover:bg-indigo-500 
                text-sm 
                uppercase 
                p-2 
                flex-initial
                rounded 
                " %>
  <% if user_signed_in? %>
    <% if @message.user_id == current_user.id %>
      <%= link_to "Edit", edit_message_path(@message),
            class: "border-2 
                    border-blue-400 
                    hover:border-blue-500 
                    text-gray-700 
                    hover:text-blue-800
                    hover:bg-blue-500 
                    text-sm 
                    uppercase 
                    p-2 
                    rounded 
                    ml-2" %>
      <%= link_to "Delete", message_path(@message), method: :delete,
            data: { confirm: "Are you sure?"},
            class: "border-2 
                    border-pink-400 
                    hover:border-pink-500 
                    text-gray-700 
                    hover:text-pink-800
                    hover:bg-pink-500 
                    text-sm 
                    uppercase 
                    p-2 
                    flex-initial
                    rounded 
                    ml-2" %>
    <% end %>
  <% end %>
</div>